/**
 * assign-uids.gs - give every facility row a short key that is assigned once
 * and never reused.
 *
 * WHY
 *   FAC-### and INC-### are regenerated by the workbook - both sequences are
 *   dense with no gaps at all, which only happens if the numbers shift when a
 *   row is deleted.
 *
 *   Inside the spreadsheet that is harmless. The _de and _ar tabs derive
 *   everything by lookup, so when a base id shifts the translation shifts with
 *   it; measured coverage is 100% with zero untranslated cells, which is a
 *   formula signature, not typed text. Nothing drifts there.
 *
 *   The breakage is outside the spreadsheet. tools/_records_manifest.json
 *   remembers each facility's published slug keyed by (section, id, lang), and
 *   reuses it forever so a live URL never changes. Delete one facility and
 *   every facility below it inherits the previous occupant's id - and with it
 *   the previous occupant's URL. 150 published hospital URLs would silently
 *   repoint to the wrong hospital, and because the slug is sticky the wrong
 *   name stays baked in.
 *
 * WHAT THIS DOES
 *   Adds a `uid` column and fills it with values like HF001. The counter lives
 *   in Script Properties, not in the sheet, so deleting the highest-numbered
 *   row can never cause its id to be handed out again. Existing uids are never
 *   touched - the script only fills blanks.
 *
 *   Sequential rather than random on purpose: at these volumes a random 4-char
 *   key collides ~38% of the time within 1,000 rows, so it would need a
 *   uniqueness check anyway. A counter is collision-free by construction,
 *   shorter, sortable and readable.
 *
 * HOW TO USE
 *   1. Paste into the workbook's Apps Script project.
 *   2. Run assignUids() once. It backfills every existing row.
 *   3. Call assignUids() at the top of syncAll() so new rows are stamped
 *      before they are ever exported.
 *
 *   Safe to re-run. It only ever writes to blank uid cells.
 *
 * SCOPE
 *   The _de and _ar tabs do not need a uid. They join on incident_id / id and
 *   that join is internally consistent, because both sides are regenerated
 *   together on every sync.
 *
 *   Incident uids are included but have no consumer today - incident fragments
 *   are built from date + attack type, not from incident_id. They exist so a
 *   future stable incident reference does not require a second migration.
 */

// Which tabs get a uid, and the prefix + width for each.
// Prefixes are per section so keys stay unique when the water, power, media
// and shelter workbooks come online.
// `key` is the column that marks a row as a real record. Rows without a value
// there are export padding or half-typed fragments, and are skipped — 53 rows
// in Hospital_incidents have stray content but no incident_id, and stamping
// them would burn ids and make junk look like records.
var UID_TARGETS = [
  { sheet: 'Hospital_facilities',   prefix: 'HF', digits: 3, key: 'id' },
  { sheet: 'Hospital_incidents',    prefix: 'HI', digits: 4, key: 'incident_id' },

  // Other sections — uncomment per workbook as each is set up.
  // { sheet: 'University_facilities',  prefix: 'UF', digits: 3, key: 'id' },
  // { sheet: 'University_incidents',   prefix: 'UI', digits: 4, key: 'incident_id' },
  // { sheet: 'Schools_facilities',     prefix: 'SF', digits: 3, key: 'id' },
  // { sheet: 'Schools_incidents',      prefix: 'SI', digits: 4, key: 'incident_id' },
  // { sheet: 'Religous_facilities',    prefix: 'RF', digits: 3, key: 'id' },
  // { sheet: 'Religous_incidents',     prefix: 'RI', digits: 4, key: 'incident_id' },
];

var UID_HEADER = 'uid';

function assignUids() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var report = [];

  UID_TARGETS.forEach(function (target) {
    var sheet = ss.getSheetByName(target.sheet);
    if (!sheet) { report.push(target.sheet + ': tab not found'); return; }
    report.push(stampSheet(sheet, target.prefix, target.digits, target.key));
  });

  var msg = report.join('\n');
  Logger.log(msg);
  try { SpreadsheetApp.getUi().alert('uid assignment\n\n' + msg); } catch (e) { /* not run from the UI */ }
}

function stampSheet(sheet, prefix, digits, keyName) {
  var lastRow = sheet.getLastRow();
  var lastCol = sheet.getLastColumn();
  if (lastRow < 2) return sheet.getName() + ': no data rows';

  var header = sheet.getRange(1, 1, 1, lastCol).getValues()[0];

  // find or create the uid column
  var uidCol = -1;
  for (var i = 0; i < header.length; i++) {
    if (String(header[i]).trim().toLowerCase() === UID_HEADER) { uidCol = i + 1; break; }
  }
  if (uidCol === -1) {
    uidCol = lastCol + 1;
    // The grid may end exactly at the last used column, in which case writing
    // to lastCol + 1 throws "range exceeds grid limits" rather than growing
    // the sheet. Add the column explicitly first.
    if (uidCol > sheet.getMaxColumns()) sheet.insertColumnAfter(lastCol);
    sheet.getRange(1, uidCol).setValue(UID_HEADER);
    // plain text, so nothing tries to read HI0001 as a number or a date
    sheet.getRange(2, uidCol, sheet.getMaxRows() - 1, 1).setNumberFormat('@');
  }

  var values = sheet.getRange(2, uidCol, lastRow - 1, 1).getValues();

  // A row is real when its key column has a value. getDataRange() reaches well
  // past the last real row, and some rows carry stray content — a leftover
  // "No", or the sheet's own View button — without ever being a record.
  var rowData = sheet.getRange(2, 1, lastRow - 1, lastCol).getValues();
  var keyCol = -1;
  for (var k = 0; k < header.length; k++) {
    if (String(header[k]).trim().toLowerCase() === String(keyName).toLowerCase()) { keyCol = k; break; }
  }
  if (keyCol === -1) return sheet.getName() + ': key column "' + keyName + '" not found — nothing written';

  var counter = nextCounter(prefix, values);
  var written = 0, skipped = 0, blankRows = 0;

  for (var r = 0; r < values.length; r++) {
    if (String(values[r][0]).trim() !== '') { skipped++; continue; }

    if (String(rowData[r][keyCol]).trim() === '') { blankRows++; continue; }

    values[r][0] = prefix + pad(counter, digits);
    counter++;
    written++;
  }

  if (written) {
    sheet.getRange(2, uidCol, values.length, 1).setValues(values);
  }
  saveCounter(prefix, counter);

  return sheet.getName() + ' [col ' + colLetter(uidCol) + ']: ' + written +
         ' assigned, ' + skipped + ' already had one, ' + blankRows +
         ' non-record rows skipped (next ' + prefix + pad(counter, digits) + ')';
}

/**
 * The next number to hand out.
 *
 * Held in Script Properties rather than derived from the sheet, because
 * max(existing)+1 hands the same id out again as soon as the highest row is
 * deleted — which is the exact failure this column exists to prevent. The
 * sheet is only consulted to raise a counter that has fallen behind.
 */
function nextCounter(prefix, existingValues) {
  var props = PropertiesService.getScriptProperties();
  var key = 'uidNext_' + prefix;
  var stored = parseInt(props.getProperty(key), 10);
  if (isNaN(stored) || stored < 1) stored = 1;

  var highest = 0;
  var re = new RegExp('^' + prefix + '(\\d+)$');
  existingValues.forEach(function (row) {
    var m = re.exec(String(row[0]).trim());
    if (m) { var n = parseInt(m[1], 10); if (n > highest) highest = n; }
  });

  return Math.max(stored, highest + 1);
}

function saveCounter(prefix, value) {
  PropertiesService.getScriptProperties()
    .setProperty('uidNext_' + prefix, String(value));
}

/** 1 -> A, 27 -> AA. Only used to say where the column landed. */
function colLetter(n) {
  var s = '';
  while (n > 0) { var r = (n - 1) % 26; s = String.fromCharCode(65 + r) + s; n = (n - 1 - r) / 26; }
  return s;
}

function pad(n, width) {
  var s = String(n);
  while (s.length < width) s = '0' + s;
  return s;
}

/**
 * Check for duplicates without changing anything. Worth running once after
 * the first backfill, and any time rows have been copy-pasted between tabs —
 * pasting carries the uid with it, which is the one way duplicates appear.
 */
function auditUids() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var out = [];

  UID_TARGETS.forEach(function (target) {
    var sheet = ss.getSheetByName(target.sheet);
    if (!sheet) return;
    var lastRow = sheet.getLastRow(), lastCol = sheet.getLastColumn();
    if (lastRow < 2) return;

    var header = sheet.getRange(1, 1, 1, lastCol).getValues()[0];
    var uidCol = -1;
    for (var i = 0; i < header.length; i++) {
      if (String(header[i]).trim().toLowerCase() === UID_HEADER) { uidCol = i + 1; break; }
    }
    if (uidCol === -1) { out.push(target.sheet + ': no uid column yet'); return; }

    var keyCol = -1;
    for (var k = 0; k < header.length; k++) {
      if (String(header[k]).trim().toLowerCase() === String(target.key).toLowerCase()) { keyCol = k; break; }
    }

    var seen = {}, dupes = [], missing = 0;
    var rows = sheet.getRange(2, 1, lastRow - 1, lastCol).getValues();
    rows.forEach(function (row) {
      if (keyCol === -1 || String(row[keyCol]).trim() === '') return;
      var v = String(row[uidCol - 1]).trim();
      if (!v) { missing++; return; }
      if (seen[v]) { dupes.push(v); } else { seen[v] = true; }
    });

    out.push(target.sheet + ': ' + Object.keys(seen).length + ' unique, ' +
             missing + ' missing, ' + dupes.length + ' duplicated' +
             (dupes.length ? ' [' + dupes.slice(0, 8).join(', ') + ']' : ''));
  });

  var msg = out.join('\n');
  Logger.log(msg);
  try { SpreadsheetApp.getUi().alert('uid audit\n\n' + msg); } catch (e) { /* headless */ }
}

/** Convenience menu so this can be run without opening the script editor. */
function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('PalGenoPedia')
    .addItem('Assign missing uids', 'assignUids')
    .addItem('Audit uids', 'auditUids')
    .addToUi();
}
