#!/usr/bin/env python3
"""
seo_inject.py — inject the shared SEO <head> block into every served page.

READS   ../data/events.json      (for the compact ItemList structured data)
        each served *.html       (title / meta description already authored per page)
WRITES  each served *.html       (idempotent, marker-delimited block in <head>)

The block carries, per page:
  * <link rel="canonical">                    - one indexable URL per page
  * Open Graph + Twitter Card                 - so shared links render a card
  * <link rel="alternate"> Atom + RSS         - feed discovery
  * preconnect/dns-prefetch for the CDN       - shaves the third-party handshake
  * JSON-LD appropriate to the page type      - WebSite / CollectionPage /
                                                Dataset / ItemList / BreadcrumbList

Everything sits between SEO_START and SEO_END markers, so re-running replaces
the block rather than stacking duplicates. Nothing outside the markers is touched.

Deliberately NOT emitted:
  * hreflang - the de/ar translations are applied client-side on the *same*
    URL. hreflang requires a distinct URL per language; emitting it here would
    point Google at URLs that do not exist.

Usage:  python tools/seo_inject.py [--check]
        --check reports what would change and writes nothing.
"""
import json, os, re, sys, datetime

BASE = "https://palgenopedia.org"
SITE = "PalGenoPedia"
OG_IMAGE = BASE + "/images/og-card.png"
OG_ALT = "PalGenoPedia - documented war crimes, massacres and humanitarian violations concerning Palestine, 1948 to present"
TODAY = datetime.date.today().isoformat()

START = "<!-- SEO_START - generated by tools/seo_inject.py - do not edit by hand -->"
END = "<!-- SEO_END -->"
NAV_START = "<!-- SEO_NAV_START - generated by tools/seo_inject.py - do not edit by hand -->"
NAV_END = "<!-- SEO_NAV_END -->"

# Pages beyond the footer partial's own list that a crawler still needs a path
# to. (label, href) - appended after the footer links, deduped on href.
EXTRA_NAV = [
    ("Historical Events", "/historical-events/"),
    ("Ethnic Cleansing, 1948", "/historical-events/ethnic-cleansing/"),
    ("Testimonies", "/historical-events/testimonies/"),
    ("Volunteer", "/volunteer.html"),
]

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SKIP_DIRS = ('.git', 'draft', '.idea', '.claude')
# Every generator that writes finished pages must be listed here, or
# seo_inject will stamp a second canonical and JSON-LD block into its
# output and have the work discarded on the next build.
MANIFESTS = [os.path.join(HERE, '_records_manifest.json'),
             os.path.join(HERE, '_history_manifest.json')]

# Pages that are collections of documented records rather than prose
SECTION_OF = {
    'war-crimes/index.html': ('War Crimes Statistics', None),
    'hunger-crisis-stats.html': ('Hunger Crisis Statistics', None),
    'historical-events/index.html': ('Historical Events', None),
    'volunteer.html': ('Volunteer', None),
}
BREADCRUMB_PARENT = {
    # The two hunger-crisis detail pages live under /war-crimes/ (matching the
    # four API-driven stat pages already there) but are topically children of
    # the Hunger Crisis hub, not the War Crimes one. These two exact paths
    # must be matched before the generic 'war-crimes/' prefix below, or that
    # prefix would win and mislabel their breadcrumb.
    'war-crimes/total-starvation/': ('Hunger Crisis Statistics', '/hunger-crisis-stats.html'),
    'war-crimes/children-starvation/': ('Hunger Crisis Statistics', '/hunger-crisis-stats.html'),
    # The four API-driven stat pages moved out of Pages/War_Crimes_Stats/ and
    # into /war-crimes/, alongside the generated record sections. They are
    # still children of the war-crimes hub, so they keep its crumb.
    'war-crimes/': ('War Crimes Statistics', '/war-crimes/'),
    'Pages/War_Crimes_Stats/': ('War Crimes Statistics', '/war-crimes/'),
    'Pages/Hunger_Crisis/': ('Hunger Crisis Statistics', '/hunger-crisis-stats.html'),
    # The hub and the ethnic-cleansing page moved into /historical-events/;
    # the massacres archive stays beside its CSVs. All three are children
    # of the same hub, so they share its crumb.
    'historical-events/': ('Historical Events', '/historical-events/'),
    'Pages/Historical_Massacres/': ('Historical Events', '/historical-events/'),
}

# Interactive Pages/ views that a proper generated section now supersedes.
# No page on the public site links to any of these any more (build_records.py
# and build_history.py stopped emitting the "Interactive database" back-link,
# and the two remaining hand-written references - the historical-events hub's
# villages-map card and 404.html - were repointed at the generated pages).
# The files stay on the server and load correctly for anyone who already has
# the URL; they simply stop being something the public site, the sitemap, or
# a search engine is told to find. noindex is the right tool for exactly this
# - unlike a sitemap/link removal alone, it also covers a visitor arriving via
# an old bookmark or a stale external backlink.
NOINDEX_PATHS = {
    'Pages/War_Crimes_Stats/stat-hospitals-attacked.html',
    'Pages/War_Crimes_Stats/stat-schools-destroyed.html',
    'Pages/War_Crimes_Stats/stat-universities-damaged.html',
    'Pages/War_Crimes_Stats/stat-religious-sites.html',
    'Pages/Historical_Massacres/massacres.html',
}


def is_redirect_stub(path):
    """True for the placeholder left at a URL that moved.

    A stub carries a canonical to its replacement and nothing else worth
    indexing. It must not be listed in the sitemap (which would advertise a
    URL we are trying to retire) and must not have an SEO block injected
    (which would overwrite the canonical that makes the redirect work)."""
    try:
        with open(path, encoding='utf-8') as fh:
            head = fh.read(1200)
    except Exception:
        return False
    return 'http-equiv="refresh"' in head


def generated_paths():
    """Page paths owned by tools/build_records.py.

    Those pages already carry a canonical, Open Graph and JSON-LD written at
    generation time, and are rewritten from the CSVs on every build. Injecting
    a block here would duplicate all of it, and be silently discarded on the
    next run."""
    out = set()
    for man in MANIFESTS:
        if not os.path.exists(man):
            continue
        try:
            pages = json.load(open(man, encoding='utf-8'))['pages']
        except Exception:
            continue
        out |= {x['path'].strip('/') for x in pages if x.get('path')}
    return out


def page_href(rel):
    """The URL a served file is actually reached at.

    A directory index is served at the directory, so war-crimes/x/index.html
    is /war-crimes/x/ - the URL every link and the sitemap use. A canonical
    pointing at the .../index.html form would claim a second URL for it."""
    if rel == 'index.html':
        return '/'
    if rel.endswith('/index.html'):
        return '/' + rel[:-len('index.html')]
    return '/' + rel


def site_nav_links():
    """(label, absolute href) for every page the site nav points at.

    Parsed from partials/site-footer.html so there is ONE source of truth: the
    footer JS and this static fallback cannot drift apart, because they read the
    same file. Relative hrefs are made absolute - the partial is written to be
    rewritten per-page by footer-init.js rewriteFooterLinks(), and a static copy
    has to resolve from any depth on its own.
    """
    src = os.path.join(ROOT, 'partials', 'site-footer.html')
    out, seen = [], set()
    try:
        html = open(src, encoding='utf-8').read()
    except OSError:
        html = ''
    for href, label in re.findall(r'<a[^>]+href="([^"]+)"[^>]*>(.*?)</a>', html, re.S):
        if href.startswith(('http', 'mailto:', 'tel:', '#')):
            continue
        if not href.startswith('/'):
            href = '/' + href
        if href == '/index.html':
            href = '/'
        # Drop the status badge (<span class="status-badge">ACTIVE</span>) before
        # flattening tags - it is UI chrome, not part of the link's anchor text,
        # and anchor text is a ranking signal for the page it points at.
        label = re.sub(r'<span[^>]*status-badge[^>]*>.*?</span>', '', label, flags=re.S)
        label = re.sub(r'<[^>]+>', '', label)
        label = "".join(c for c in label if c.isalnum() or c in " ,.-'/&").strip()
        if not label or href in seen:
            continue
        seen.add(href)
        out.append((label, href))
    for label, href in EXTRA_NAV:
        if href not in seen:
            seen.add(href)
            out.append((label, href))
    return out


def nav_block():
    """A real <a href> for every primary page, as the no-JS / non-rendering
    crawler baseline.

    Why this exists: the site header is injected by header-component.js with
    insertAdjacentHTML, and the footer by footer-init.js with a runtime
    fetch() of partials/site-footer.html. So in the SERVED html the homepage
    carried five internal links and the war-crimes hub carried three - none of
    them to a section index, because those cards are built in a <script> too.
    A crawl of the static site found 424 of 518 pages unreachable from /,
    including 262 that sitemap.xml asks Google to index. Googlebot renders JS
    eventually; GPTBot / ClaudeBot / CCBot - which robots.txt explicitly
    invites - largely do not.

    Same pattern build_history.py _static_list() already uses for the timeline:
    put the static list inside the container the JS overwrites, so it costs
    nothing visually and everything is in the HTML a parser sees.
    """
    L = [NAV_START,
         '<nav class="static-site-nav" aria-label="Site sections"'
         ' style="max-width:1100px;margin:0 auto;padding:1.5rem 1rem;'
         'font-size:.95rem;line-height:2">']
    for label, href in site_nav_links():
        L.append('  <a href="%s" style="margin-right:1.25rem;white-space:nowrap">%s</a>'
                 % (href, esc(label)))
    L.append('</nav>')
    L.append(NAV_END)
    return chr(10).join(L)


def served_pages():
    out = []
    generated = generated_paths()
    for dp, dn, fn in os.walk(ROOT):
        dn[:] = [d for d in dn if d not in SKIP_DIRS]
        for f in fn:
            if not f.endswith('.html'):
                continue
            rel = os.path.relpath(os.path.join(dp, f), ROOT).replace("\\", "/")
            if rel.startswith('data/jsonld/') or rel.startswith('partials/'):
                continue
            # 404.html authors its own head. It must stay noindex and must not
            # carry a self-canonical - GitHub Pages serves it for every missing
            # path, so a canonical here would claim one URL for all of them.
            if rel == '404.html':
                continue
            if rel.endswith('/index.html') and rel[:-len('/index.html')] in generated:
                continue
            if is_redirect_stub(os.path.join(dp, f)):
                continue
            out.append(rel)
    return sorted(out)


def grab(pat, txt):
    m = re.search(pat, txt, re.I | re.S)
    return re.sub(r'\s+', ' ', m.group(1)).strip() if m else None


def esc(s):
    return (s or '').replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;')


def load_events():
    p = os.path.join(ROOT, 'data', 'events.json')
    if not os.path.exists(p):
        return []
    d = json.load(open(p, encoding='utf-8'))
    return d if isinstance(d, list) else d.get('events', [])


TIMELINE_PAGE = "/historical-events/massacres/timeline.html"


def _history_slug_map():
    """id -> canonical English record URL, from the history manifest, so the
    ItemList points at the real generated event pages rather than the old
    interactive archive."""
    out = {}
    p = os.path.join(HERE, '_history_manifest.json')
    if os.path.exists(p):
        try:
            for x in json.load(open(p, encoding='utf-8'))['pages']:
                if x.get('lang') == 'en' and x.get('id') and x.get('path'):
                    out[x['id']] = x['path']
        except Exception:
            pass
    return out


def event_items(events, period=None, limit=None):
    """Compact ItemList entries - name/date/url only. The full record already
    lives in data/events.json and the per-event .jsonld files; repeating all of
    it inline would add ~250 KB per page for no ranking benefit."""
    sel = [e for e in events if (period is None or e.get('period') == period)]
    sel.sort(key=lambda e: e.get('date_start') or '')
    if limit:
        sel = sel[:limit]
    hist = _history_slug_map()
    items = []
    for i, e in enumerate(sel, 1):
        if e['id'] in hist:
            url = BASE + hist[e['id']]
        else:
            url = "%s%s#event/%s" % (BASE, TIMELINE_PAGE, e['id'])
        items.append({
            "@type": "ListItem",
            "position": i,
            "item": {
                "@type": "Event",
                "name": e.get('title'),
                "startDate": e.get('date_start'),
                "url": url,
            }
        })
    return items


def breadcrumb(rel, title):
    crumbs = [{"@type": "ListItem", "position": 1, "name": "Home", "item": BASE + "/"}]
    pos = 2
    for prefix, (label, href) in BREADCRUMB_PARENT.items():
        # A section hub matches its own prefix. Without this it would appear
        # twice in its own trail, as parent and as self.
        if href == page_href(rel):
            break
        if rel.startswith(prefix):
            crumbs.append({"@type": "ListItem", "position": pos, "name": label, "item": BASE + href})
            pos += 1
            break
    crumbs.append({"@type": "ListItem", "position": pos, "name": title, "item": BASE + page_href(rel)})
    return {"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": crumbs}


def jsonld_for(rel, title, desc, events):
    canonical = BASE + page_href(rel)
    blocks = []

    if rel == 'index.html':
        blocks.append({
            "@context": "https://schema.org",
            "@type": "WebSite",
            "@id": BASE + "/#website",
            "url": BASE + "/",
            "name": SITE,
            "description": desc,
            "inLanguage": ["en", "ar", "de"],
            "publisher": {"@id": BASE + "/#org"},
        })
        blocks.append({
            "@context": "https://schema.org",
            "@type": "Organization",
            "@id": BASE + "/#org",
            "name": SITE,
            "url": BASE + "/",
            "logo": OG_IMAGE,
            "description": "An open documentation resource of verified war crimes, massacres, and humanitarian violations concerning Palestine, 1948-present.",
        })
        blocks.append({
            "@context": "https://schema.org",
            "@type": "Dataset",
            "@id": BASE + "/data/events.json",
            "name": "PalGenoPedia Documented Events Dataset",
            "description": "Verified war crimes, massacres and humanitarian violations concerning Palestine, 1948-present. Every figure carries provenance and a verification status.",
            "url": BASE + "/data/events.json",
            "license": "https://creativecommons.org/licenses/by/4.0/",
            "isAccessibleForFree": True,
            "creator": {"@id": BASE + "/#org"},
            "distribution": [
                {"@type": "DataDownload", "encodingFormat": "application/json", "contentUrl": BASE + "/data/events.json"},
                {"@type": "DataDownload", "encodingFormat": "text/csv", "contentUrl": BASE + "/data/events.csv"},
                {"@type": "DataDownload", "encodingFormat": "application/x-ndjson", "contentUrl": BASE + "/data/events.ndjson"},
            ],
        })
    else:
        # A page that lists documented records is a CollectionPage; prose is a
        # WebPage. The stat pages under war-crimes/ are collections wherever
        # they happen to live.
        page_type = ("CollectionPage"
                     if rel in SECTION_OF or rel.startswith('Pages/')
                     or rel.startswith('war-crimes/')
                     or rel.startswith('historical-events/')
                     else "WebPage")
        blocks.append({
            "@context": "https://schema.org",
            "@type": page_type,
            "@id": canonical + "#page",
            "url": canonical,
            "name": title,
            "description": desc,
            "inLanguage": "en",
            "isPartOf": {"@id": BASE + "/#website"},
            "publisher": {"@id": BASE + "/#org"},
        })
        blocks.append(breadcrumb(rel, re.sub(r'\s*[-–—|].*$', '', title or rel).strip() or rel))

    # No ItemList is injected anywhere here any more. The one page that wants
    # one — the massacres timeline / section index — is generated by
    # build_history.py, which emits its own ItemList (every Event carrying a
    # name, startDate and the URL of its own record page). seo_inject only
    # touches hand-authored pages, and none of those are event collections.
    return blocks


def build_block(rel, title, desc, events):
    canonical = BASE + page_href(rel)
    depth = rel.count('/')
    root = '../' * depth if depth else './'
    L = [START]
    L.append('    <link rel="canonical" href="%s">' % canonical)
    L.append('    <meta property="og:type" content="website">')
    L.append('    <meta property="og:site_name" content="%s">' % SITE)
    L.append('    <meta property="og:locale" content="en_US">')
    L.append('    <meta property="og:title" content="%s">' % esc(title))
    if desc:
        L.append('    <meta property="og:description" content="%s">' % esc(desc))
    L.append('    <meta property="og:url" content="%s">' % canonical)
    L.append('    <meta property="og:image" content="%s">' % OG_IMAGE)
    L.append('    <meta property="og:image:width" content="1200">')
    L.append('    <meta property="og:image:height" content="630">')
    L.append('    <meta property="og:image:alt" content="%s">' % esc(OG_ALT))
    L.append('    <meta name="twitter:card" content="summary_large_image">')
    L.append('    <meta name="twitter:title" content="%s">' % esc(title))
    if desc:
        L.append('    <meta name="twitter:description" content="%s">' % esc(desc))
    L.append('    <meta name="twitter:image" content="%s">' % OG_IMAGE)
    robots = ('noindex, follow' if rel in NOINDEX_PATHS
              else 'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1')
    L.append('    <meta name="robots" content="%s">' % robots)
    L.append('    <link rel="alternate" type="application/atom+xml" title="%s - documented events" href="%sfeed.xml">' % (SITE, root))
    L.append('    <link rel="alternate" type="application/rss+xml" title="%s - documented events" href="%sfeed.rss">' % (SITE, root))
    # No preconnect/dns-prefetch: Leaflet, markercluster, PapaParse and Chart.js
    # are vendored under /js/vendor/ and /Styles/vendor/ as of 2026-08-30, so
    # there is no third-party origin left to warm up. A preconnect to a host the
    # page never contacts costs a DNS lookup and a TLS handshake for nothing.
    for b in jsonld_for(rel, title, desc, events):
        L.append('    <script type="application/ld+json">')
        L.append(json.dumps(b, ensure_ascii=False, indent=2))
        L.append('    </script>')
    L.append('    ' + END)
    return "\r\n".join(L)


def main():
    check = '--check' in sys.argv
    events = load_events()
    pages = served_pages()
    changed = 0
    for rel in pages:
        p = os.path.join(ROOT, rel)
        raw = open(p, 'rb').read().decode('utf-8')
        crlf = raw.count('\r\n') > 0
        txt = raw.replace('\r\n', '\n')

        title = grab(r'<title[^>]*>(.*?)</title>', txt)
        desc = grab(r'<meta[^>]+name=["\']description["\'][^>]+content=["\'](.*?)["\']', txt)
        if not title:
            print("  SKIP (no <title>): %s" % rel)
            continue

        block = build_block(rel, title, desc, events).replace('\r\n', '\n')

        if START in txt:
            new = re.sub(re.escape(START) + r'.*?' + re.escape(END), block, txt, flags=re.S)
        else:
            m = re.search(r'</head>', txt, re.I)
            if not m:
                print("  SKIP (no </head>): %s" % rel)
                continue
            new = txt[:m.start()] + block + "\n" + txt[m.start():]

        # ── static site nav ────────────────────────────────────────────
        # Skipped for the noindex Pages/ views: no crawl value, and they are
        # developer surfaces, not part of the public link graph.
        if rel not in NOINDEX_PATHS:
            nav = nav_block()
            if NAV_START in new:
                new = re.sub(re.escape(NAV_START) + r'.*?' + re.escape(NAV_END),
                             nav, new, flags=re.S)
            else:
                # Preferred home: INSIDE #footer-placeholder. footer-init.js
                # does placeholder.innerHTML = html on load, so the static copy
                # is replaced by the real footer and nothing renders twice.
                ph = re.search(r'(<div[^>]*id="footer-placeholder"[^>]*>)(.*?)(</div>)',
                               new, re.S)
                if ph:
                    NL = chr(10)
                    new = new[:ph.start(2)] + NL + nav + NL + new[ph.end(2):]
                else:
                    b = re.search(r'</body>', new, re.I)
                    if b:
                        new = new[:b.start()] + nav + chr(10) + new[b.start():]
                    else:
                        print("  SKIP (no footer-placeholder and no </body>): %s" % rel)

        if new == txt:
            continue
        changed += 1
        print("  %-54s %s" % (rel, 'would update' if check else 'updated'))
        if not check:
            out = new.replace('\n', '\r\n') if crlf else new
            open(p, 'wb').write(out.encode('utf-8'))

    print("\n%s %d of %d served pages" % ('would change' if check else 'changed', changed, len(pages)))


if __name__ == '__main__':
    main()
